/*
 * Copyright (c) 2021 SQLines
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Implementation of the settings window.
 * <p>
 *
 * Interfaces:
 * <p>
 * {@link com.sqlines.studio.view.settings.SettingsWindowView} -
 * interface through with the presenter / controller can interact with the settings window UI.
 * Provides methods for work with the settings window.
 *
 * <p>
 * Classes:
 * <p>
 * {@link com.sqlines.studio.view.settings.SettingsWindow} -
 * the concrete settings window that implements
 * {@link com.sqlines.studio.view.settings.SettingsWindowView}.
 *
 * <p>
 * Packages:
 * <p>
 * {@link com.sqlines.studio.view.settings.event} -
 * contains events generated by the settings window.
 */
package com.sqlines.studio.view.settings;
